import yfinance as yf
import pandas as pd
import warnings
from datetime import datetime, timedelta

# Suppress pandas FutureWarnings which occur inside yfinance and when dealing with single-element Series
warnings.simplefilter(action='ignore', category=FutureWarning)

# Top 20 European Stocks (using US ADR tickers for better Yahoo Finance compatibility)
EURO_STOCKS = {
    "ASML Holding": "ASML",
    "LVMH": "LVMUY",
    "SAP": "SAP",
    "Siemens": "SIEGY",
    "TotalEnergies": "TTE",
    "L'Oreal": "LRLCY",
    "Sanofi": "SNY",
    "Schneider Electric": "SBGSY",
    "Allianz": "ALIZY",
    "Air Liquide": "AIQUY",
    "Hermes": "HESAY",
    "Deutsche Telekom": "DTEGY",
    "Airbus": "EADSY",
    "Iberdrola": "IBDRY",
    "EssilorLuxottica": "ESLOY",
    "Enel": "ENLAY",
    "BNP Paribas": "BNPQY",
    "Vinci": "VCISY",
    "Intesa Sanpaolo": "ISNPY",
    "Banco Santander": "SAN"
}

def get_historical_data(ticker: str, days: int = 30):
    """Fetches historical daily stock data for the past `days` days."""
    end_date = datetime.today()
    start_date = end_date - timedelta(days=days)
    
    # Download data
    data = yf.download(ticker, start=start_date.strftime('%Y-%m-%d'), end=end_date.strftime('%Y-%m-%d'))
    
    if data.empty:
        return pd.DataFrame()
        
    data.reset_index(inplace=True)
    
    # Flatten MultiIndex columns if generated by newer yfinance versions
    if isinstance(data.columns, pd.MultiIndex):
        data.columns = [col[0] if col[0] != '' else col[1] for col in data.columns]
        
    return data

def get_performance_summary(data: pd.DataFrame):
    """Calculates start price, end price, and percent change."""
    if data.empty:
        return None
    
    def _to_float(val):
        if isinstance(val, pd.Series):
            return float(val.iloc[0])
        return float(val)
        
    def _to_str(val):
        if isinstance(val, pd.Series):
            val = val.iloc[0]
        if hasattr(val, 'strftime'):
            return val.strftime('%Y-%m-%d')
        return str(val).split(' ')[0]

    start_price = data['Close'].iloc[0]
    end_price = data['Close'].iloc[-1]
    highest_price = data['High'].max()
    lowest_price = data['Low'].min()
    percent_change = ((end_price - start_price) / start_price) * 100
    
    # yfinance reset_index renames the index to 'Date' or 'Datetime'
    date_col = 'Date' if 'Date' in data.columns else 'Datetime'
    start_date = data[date_col].iloc[0] if date_col in data.columns else None
    end_date = data[date_col].iloc[-1] if date_col in data.columns else None
    
    return {
        "start_price": _to_float(start_price),
        "end_price": _to_float(end_price),
        "highest_price": _to_float(highest_price),
        "lowest_price": _to_float(lowest_price),
        "percent_change": _to_float(percent_change),
        "start_date": _to_str(start_date) if start_date is not None else "Unknown",
        "end_date": _to_str(end_date) if end_date is not None else "Unknown"
    }

if __name__ == "__main__":
    # Test script
    ticker = EURO_STOCKS["SAP"]
    print(f"Fetching data for {ticker}...")
    df = get_historical_data(ticker, days=30)
    print(df.head())
    print(get_performance_summary(df))
